model_list: []

general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
  store_model_in_db: true
  database_url: "os.environ/DATABASE_URL"

litellm_settings:
  drop_params: true
  telemetry: false
